export const AILA_RUNTIME_SDK_VERSION = 1

export {
  type AgentEvent,
  type AgentEventSink,
  type AgentEventType,
  getModelInfo,
  type ModelSelection,
  type UsageInfo,
} from '../main/agent'
export {
  AGENT_PROFILES,
  type AgentProfile,
  type AgentProfileId,
  type BuiltinAgentProfileId,
  getAgentProfile,
  isBuiltinAgentProfileId,
  normalizeBuiltinAgentProfileId,
  normalizeChatAgentProfileId,
} from '../main/agent-profile'
export {
  type AgentEventAppendResult,
  AILA_AGENT_EVENT_SCHEMA_VERSION,
  AILA_CONVERSATION_META_SCHEMA_VERSION,
  AILA_PERSISTED_MESSAGE_SCHEMA_VERSION,
  type ConversationActivity,
  type ConversationActivityState,
  type ConversationInterruptedRecoveryOptions,
  type ConversationRecord,
  type ConversationRuntimePendingApproval,
  type ConversationRuntimeReplayState,
  type ConversationRuntimeReplayTurn,
  type ConversationRuntimeStatePhase,
  type ConversationSummary,
  type ConversationUsage,
  createInterruptedConversationRecoveryEvent,
  type DocRefRewrite,
  type PersistedAgentEvent,
  type PersistedBlock,
  type PersistedImageBlock,
  type PersistedMessage,
  type PersistedTextBlock,
  type PersistedToolCallBlock,
  replayConversationActivity,
  replayConversationRuntimeState,
} from '../main/conversations'
export {
  type ExtensionProfileReport,
  type ExtensionReport,
  type ExtensionReportError,
  type ExtensionReportErrorKind,
  type ExtensionToolPackReport,
  getExtensionReport,
} from '../main/extensions'
export {
  applyFindReplace,
  type FindReplaceEdit,
  type FindReplaceFailure,
  type FindReplacePatch,
  type FindReplaceResult,
  formatFindReplaceErrors,
} from '../main/find-replace'
export {
  configureDataDir,
  getConversationsDir,
  getDataDir,
  getImagesDir,
  getProfilesDir,
  getSettingsPath,
  getToolPacksDir,
} from '../main/paths'
export {
  type AgentProfileManifest,
  AILA_PROFILE_MANIFEST_SCHEMA_VERSION,
  type LoadedAgentProfile,
  loadAgentProfileFromManifest,
  loadAgentProfileManifest,
  loadAgentProfilesFromDir,
  parseAgentProfileManifest,
} from '../main/profile-loader'
export {
  type ActiveAssistantTurn,
  AgentRuntime,
  type AgentRuntimeEvent,
  type AgentRuntimeEventMap,
  type AgentRuntimeHost,
  type AgentRuntimeOptions,
  type AgentRuntimeStore,
  AILA_RUNTIME_EVENT_SCHEMA_VERSION,
  AILA_RUNTIME_EVENT_TYPES,
  type AilaRuntimeEventType,
  type ConversationAbortReason,
  createRuntimeEvent,
  isRuntimeEventType,
  type RuntimeAppendUserMessageInput,
  type RuntimeCreateConversationInput,
  type RuntimeListConversationsInput,
  type RuntimeRecordAgentEventInput,
  type RuntimeRetryLastInput,
  type RuntimeSendInput,
  type RuntimeSendResult,
  type RuntimeTransientContextInput,
} from '../main/runtime'
export {
  configuredProviders,
  loadSettings,
  resolveApiKey,
  type Settings,
  saveSettings,
} from '../main/settings'
export {
  AILA_TOOL_PACK_MANIFEST_FILE,
  AILA_TOOL_PACK_MANIFEST_SCHEMA_VERSION,
  type LoadedToolPack,
  loadToolPackFromManifest,
  loadToolPackManifest,
  loadToolPacksFromDir,
  parseToolPackManifest,
  type ToolPackManifest,
} from '../main/tool-pack-loader'
export {
  BUILTIN_TOOL_PACKS,
  createDefaultToolRegistry,
  createToolRegistry,
  evaluateToolPolicy,
  executeTool,
  getToolDefinitionsForProfile,
  type ImageSideChannelBlock,
  summarizeToolTarget,
  TOOL_DEFINITIONS,
  TOOL_SPECS,
  type ToolAccess,
  type ToolActivityTarget,
  type ToolApprovalRequest,
  type ToolDefinition,
  type ToolHandler,
  type ToolMetadata,
  type ToolPack,
  type ToolPackEntry,
  type ToolPolicyAction,
  type ToolPolicyDecision,
  type ToolPolicyEvaluator,
  type ToolPolicyRequest,
  type ToolRegistry,
  type ToolScope,
  type ToolSpec,
  type ToolWorkspaceRoot,
} from '../main/tools'
export {
  findModel,
  IMAGE_MODEL_CATALOG,
  type ImageModelEntry,
  MODEL_CATALOG,
  type ModelEntry,
  type ModelTag,
  PROVIDER_LABELS,
  PROVIDER_ORDER,
  type ProviderId,
} from '../shared/models'
