// Re-exports renderer-facing types from preload so renderer code doesn't have
// to dig into ../../preload paths.
export type {
  AgentEventType,
  AgentProfile,
  AgentProfileId,
  BuiltinAgentProfileId,
  ChatDoneEvent,
  ChatErrorEvent,
  ChatMessage,
  ChatStreamEventBase,
  ConversationRecord,
  ConversationSummary,
  ConversationUsage,
  DocPatch,
  DocRecord,
  DocSummary,
  ImageBlockEvent,
  ModelInfo,
  ModelSelection,
  OrCatalog,
  OrFamily,
  OrModel,
  PersistedAgentEvent,
  PersistedBlock,
  PersistedImageBlock,
  PersistedMessage,
  PersistedTextBlock,
  PersistedToolCallBlock,
  ProviderId,
  ReasoningDeltaEvent,
  SendResult,
  Settings,
  SettingsState,
  TextDeltaEvent,
  ToolApprovalRequestEvent,
  ToolApprovalResponse,
  ToolCallArgsDeltaEvent,
  ToolCallPayload,
  ToolCallResultEvent,
  ToolCallStartEvent,
  UsageInfo,
} from '../../preload/index'
