import type { AgentRuntimeStore } from '@aila/agent'
import {
  appendAgentEventAndTouchConversation,
  appendPlanRevision,
  createConversation,
  createPlan,
  deleteConversation,
  getAgentRunCheckpoint,
  getConversation,
  getPlan,
  listAgentEvents,
  listAgentRunArtifacts,
  listAgentRunCheckpoints,
  listConversations,
  listPlans,
  recordConversationContextTurnLedger,
  recoverInterruptedConversationActivityResults,
  renameConversation,
  saveAgentRunArtifact,
  saveAgentRunCheckpoint,
  setConversationContextCheckpoint,
  setConversationUsage,
  updatePlan,
  upsertMessage,
} from './conversations'

export function createPersistedRuntimeStore(): AgentRuntimeStore {
  return {
    createConversation,
    getConversation,
    saveMessage: upsertMessage,
    recordAgentEvent: appendAgentEventAndTouchConversation,
    listConversations,
    listAgentEvents,
    recoverInterruptedActivities: recoverInterruptedConversationActivityResults,
    renameConversation,
    recordUsage: setConversationUsage,
    saveContextCheckpoint: setConversationContextCheckpoint,
    recordContextTurnLedger: recordConversationContextTurnLedger,
    saveRunCheckpoint: saveAgentRunCheckpoint,
    getRunCheckpoint: getAgentRunCheckpoint,
    listRunCheckpoints: listAgentRunCheckpoints,
    saveRunArtifact: saveAgentRunArtifact,
    listRunArtifacts: listAgentRunArtifacts,
    createPlan,
    getPlan,
    listPlans,
    updatePlan,
    appendPlanRevision,
    deleteConversation,
  }
}
