import type { WorkbenchStore } from '@aila/agent'
import {
  appendPlanRevision,
  appendRunEventAndTouchConversation,
  createConversation,
  createPlan,
  deleteConversation,
  getConversation,
  getPlan,
  getRunCheckpoint,
  listConversations,
  listPlans,
  listRunArtifacts,
  listRunCheckpoints,
  listRunEvents,
  recordConversationContextTurnLedger,
  recoverInterruptedConversationActivityResults,
  renameConversation,
  saveRunArtifact,
  saveRunCheckpoint,
  setConversationContextCheckpoint,
  setConversationUsage,
  updatePlan,
  upsertMessage,
} from './conversations'

export function createPersistedRuntimeStore(): WorkbenchStore {
  return {
    createConversation,
    getConversation,
    saveMessage: upsertMessage,
    recordRunEvent: appendRunEventAndTouchConversation,
    listConversations,
    listRunEvents,
    recoverInterruptedActivities: recoverInterruptedConversationActivityResults,
    renameConversation,
    recordUsage: setConversationUsage,
    saveContextCheckpoint: setConversationContextCheckpoint,
    recordContextTurnLedger: recordConversationContextTurnLedger,
    saveRunCheckpoint: saveRunCheckpoint,
    getRunCheckpoint: getRunCheckpoint,
    listRunCheckpoints: listRunCheckpoints,
    saveRunArtifact: saveRunArtifact,
    listRunArtifacts: listRunArtifacts,
    createPlan,
    getPlan,
    listPlans,
    updatePlan,
    appendPlanRevision,
    deleteConversation,
  }
}
