import { PencilIcon, RouteIcon, Undo2Icon } from 'lucide-react'
import type { ReactElement, ReactNode } from 'react'
import type { RuntimeRunSummary } from '../../types'
import { clockTime, readableEnum, TONE_CHIP_CLASS, toneForStatus } from './debugFormat'
import { messageText, type TranscriptCard } from './playgroundState'

interface MessageCardProps {
  card: TranscriptCard
  /** Structural mutations allowed right now (guards.canMutate). */
  mutable: boolean
  /** Non-null when this card is in edit mode. */
  draftText: string | null
  run: RuntimeRunSummary | null
  traceAvailable: boolean
  traceExpanded: boolean
  onStartEdit: () => void
  onChangeDraft: (text: string) => void
  onCancelEdit: () => void
  onSaveEdit: () => void
  onRewind: () => void
  onToggleTrace: () => void
  /** The mounted trace section when expanded. */
  children?: ReactNode
}

const ROLE_CHIP: Record<'user' | 'assistant', string> = {
  user: 'bg-[var(--signal-soft)] text-[var(--blue)]',
  assistant: 'bg-[var(--bg-soft)] text-[var(--text-soft)]',
}

/**
 * One transcript message. The card is simultaneously the editable "what if"
 * surface (edits rewrite the transcript from that point) and, for generated assistant
 * messages, the anchor of the "what actually happened" trace.
 */
export function MessageCard({
  card,
  mutable,
  draftText,
  run,
  traceAvailable,
  traceExpanded,
  onStartEdit,
  onChangeDraft,
  onCancelEdit,
  onSaveEdit,
  onRewind,
  onToggleTrace,
  children,
}: MessageCardProps): ReactElement | null {
  const message = card.message
  if (!message) return null
  const editing = draftText !== null
  const nonTextBlocks = message.blocks.filter((block) => block.type !== 'text')

  return (
    <article className="group rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3.5 py-3">
      <header className="flex items-center gap-2">
        <span
          className={`rounded-full px-2 py-0.5 text-[9.5px] font-semibold uppercase tracking-wide ${ROLE_CHIP[message.role]}`}
        >
          {message.role}
        </span>
        {card.provenance === 'fabricated' && (
          <span
            className="rounded-full bg-[var(--warning-soft)] px-2 py-0.5 text-[9.5px] font-medium text-[var(--warning)]"
            title="Hand-written in the playground — never generated by a model"
          >
            fabricated
          </span>
        )}
        {message.status === 'error' && (
          <span
            className={`rounded-full px-2 py-0.5 text-[9.5px] font-medium ${TONE_CHIP_CLASS.bad}`}
          >
            error
          </span>
        )}
        {message.model && (
          <span className="truncate text-[10px] text-[var(--text-dim)]">
            {message.model.modelId}
          </span>
        )}
        {run && (
          <span
            className={`rounded-full px-2 py-0.5 text-[9.5px] font-medium ${TONE_CHIP_CLASS[toneForStatus(run.status)]}`}
          >
            run {readableEnum(run.status).toLowerCase()}
          </span>
        )}
        <span className="ml-auto shrink-0 font-mono text-[9.5px] text-[var(--text-dim)]">
          {clockTime(card.timestamp)}
        </span>
        <span className="flex shrink-0 items-center gap-0.5 opacity-0 transition-opacity group-focus-within:opacity-100 group-hover:opacity-100">
          {traceAvailable && (
            <CardIconButton
              label={traceExpanded ? 'Hide trace' : 'Show trace'}
              active={traceExpanded}
              onClick={onToggleTrace}
            >
              <RouteIcon className="size-3.5" />
            </CardIconButton>
          )}
          {mutable && !editing && (
            <>
              <CardIconButton label="Edit this message" onClick={onStartEdit}>
                <PencilIcon className="size-3.5" />
              </CardIconButton>
              <CardIconButton
                label="Rewind to before this message (removes it and everything after)"
                onClick={onRewind}
              >
                <Undo2Icon className="size-3.5" />
              </CardIconButton>
            </>
          )}
        </span>
      </header>

      {editing ? (
        <div className="mt-2">
          <textarea
            value={draftText}
            onChange={(event) => onChangeDraft(event.target.value)}
            rows={Math.min(12, Math.max(3, draftText.split('\n').length + 1))}
            className="block w-full resize-y rounded-lg border border-[var(--border-strong)] bg-[var(--textarea)] px-3 py-2 text-[12.5px] leading-relaxed text-[var(--text)] focus:outline-none"
          />
          <div className="mt-2 flex items-center justify-between gap-3">
            <p className="text-[10.5px] text-[var(--text-dim)]">
              Saving rewrites the conversation from here — later messages are removed.
            </p>
            <span className="flex shrink-0 gap-1.5">
              <button
                type="button"
                onClick={onCancelEdit}
                className="h-7 rounded-md border border-[var(--border)] px-2.5 text-[11px] font-medium text-[var(--text-soft)] hover:text-[var(--text)]"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={onSaveEdit}
                disabled={draftText.trim().length === 0}
                className="h-7 rounded-md border border-[var(--signal)] bg-[var(--signal)] px-2.5 text-[11px] font-medium text-white hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-35"
              >
                Save
              </button>
            </span>
          </div>
        </div>
      ) : (
        <div className="mt-2 whitespace-pre-wrap break-words text-[12.5px] leading-relaxed text-[var(--text)]">
          {messageText(message) || <span className="text-[var(--text-dim)]">(no text)</span>}
        </div>
      )}

      {!editing && nonTextBlocks.length > 0 && (
        <div className="mt-2 flex flex-wrap gap-1.5">
          {nonTextBlocks.map((block, index) => (
            <span
              key={
                'id' in block && typeof block.id === 'string' ? block.id : `${block.type}-${index}`
              }
              className="rounded-md border border-[var(--border)] bg-[var(--bg-soft)] px-2 py-0.5 font-mono text-[9.5px] text-[var(--text-dim)]"
            >
              {block.type === 'tool_call' && 'name' in block ? `tool: ${block.name}` : block.type}
            </span>
          ))}
        </div>
      )}

      {traceExpanded && children}
    </article>
  )
}

function CardIconButton({
  label,
  active = false,
  onClick,
  children,
}: {
  label: string
  active?: boolean
  onClick: () => void
  children: ReactNode
}): ReactElement {
  return (
    <button
      type="button"
      aria-label={label}
      title={label}
      onClick={onClick}
      className={`grid size-6 place-items-center rounded-md transition-colors hover:bg-[var(--surface-hover)] ${
        active ? 'text-[var(--signal)]' : 'text-[var(--text-dim)] hover:text-[var(--text)]'
      }`}
    >
      {children}
    </button>
  )
}
